version: "3"
services:
  api:
    build:  .
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - "./:/go/src/app"
  db:
    container_name: "db"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: dbuser
      POSTGRES_DB: database
    ports:
      - "5432:5432"