FROM golang:1.18.7-bullseye
ENV GOPATH /go
ENV GO111MODULE on

RUN apt update && \
    apt install git

RUN mkdir /go/src/app
WORKDIR /go/src/app

COPY ./api /go/src/app


CMD ["go", "run", "main.go"]