
version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.production
    tty: true
    ports:
      - "3001:8080"
    volumes:
      - "./api:/go/src/app"

  psql:
    container_name: "psql"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: dbuser
      POSTGRES_DB: database
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  proxy:
    container_name: "proxy"
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./docker/production/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/usr/share/nginx/html
    tty: true
    restart: always
  client:
    container_name: "client"
    build: 
      context: ./docker/client
      dockerfile: Dockerfile.production
    volumes:
      - type: bind
        source: ./client
        target: /usr/src/app